#!/bin/bash
# Ubuntu 22.04 LTS

# Update repos
sudo apt update -y

sudo apt -y install --no-install-recommends \
    build-essential \
    pkg-config \
    zip \
    unzip \
    v4l-utils \
    libsfml-dev \
    libopencv-dev \
    freeglut3-dev \
    libprotobuf-dev 
    
sudo apt install \
    cmake \
    python3 \
    libpython3-dev \
    python3-dev \
    python3-pip